# Generated by Django 4.0 on 2022-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_ingredient_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=500)),
            ],
        ),
    ]
