# Generated by Django 4.0 on 2022-01-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredients_selection_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='selection_count',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='food_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingredients.foodgroups'),
        ),
    ]
