# Generated by Django 4.0 on 2022-01-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_rename_food_group_ingredients_foodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='foodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='foodgroup', to='ingredients.foodgroups'),
        ),
    ]
