# Generated by Django 4.0 on 2022-01-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredients_foodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='foodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='ingredients.foodgroups'),
        ),
    ]
