# Generated by Django 4.0 on 2022-01-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_alter_ingredients_foodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='foodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing', to='ingredients.foodgroups'),
        ),
    ]
