# Generated by Django 4.0 on 2022-01-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ingredients', '0012_displayrecipe_favoriterecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayRecipe',
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
