# Generated by Django 4.0 on 2022-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_remove_favoriterecipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='ready_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
