# Generated by Django 4.0 on 2022-01-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_favoriterecipe_ready_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='cuisines',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
