# Generated by Django 4.0 on 2022-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0017_favoriterecipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='missed_ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='used_ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
