# Generated by Django 4.0 on 2022-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0018_alter_favoriterecipe_missed_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='cuisines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
